### ISSUE TITLE
Error when trying to train

### ISSUE THREAD

**Issue by ghost** [watersink/ocrsegment#1]
@watersink 
After downloading `uw3-framed-lines-degraded-000`, I extracted the images to a folder called `uw3`.
Then I ran the training command `train_test.py` and got an error message:

```
home@home-lnx:~/ocrsegment$ python3 train_test.py 
Traceback (most recent call last):
  File "train_test.py", line 254, in <module>
    train()
  File "train_test.py", line 194, in train
    dataset,one_epoch_num = get_tf_dataset(dataset_text_file="./uw3/label.txt",batch_size=batch_size,channels=batch_channel)
  File "train_test.py", line 63, in get_tf_dataset
    filenames, labels,one_epoch_num = read_labeled_image_list(dataset_text_file)
  File "train_test.py", line 53, in read_labeled_image_list
    with open(dataset_text_file,"r",encoding="utf-8") as f_l:
FileNotFoundError: [Errno 2] No such file or directory: './uw3/label.txt'
```

**Comment by watersink** [comment]
this wrong is simple, just because you don't have this file label.txt in the folder uw3，perhaps you shuould make one label.txt yourself

**Comment by christophered** [comment]
I created an empty label.txt file, then ran the command:

```
home@home-lnx:~/ocrsegment$ python3 train_test.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 947, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_test.py", line 254, in <module>
    train()
  File "train_test.py", line 194, in train
    dataset,one_epoch_num = get_tf_dataset(dataset_text_file="./uw3/label.txt",batch_size=batch_size,channels=batch_channel)
  File "train_test.py", line 72, in get_tf_dataset
    dataset = dataset.map(_parse_function)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 851, in map
    return MapDataset(self, map_func)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1839, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/function.py", line 484, in add_to_graph
    self._create_definition_if_needed()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/function.py", line 319, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/function.py", line 336, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1802, in tf_map_func
    ret = map_func(*nested_args)
  File "train_test.py", line 34, in _parse_function
    image_string = tf.read_file(filename)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 528, in read_file
    "ReadFile", filename=filename, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 533, in _apply_op_helper
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'filename' of 'ReadFile' Op has type float32 that does not match expected type of string.
```

**Comment by watersink** [comment]
you should write data label in this file,one line by one line

**Comment by MrOCR** [comment]
Here are the commands that I used to install tensorflow and the other requirements:
```
conda create -n python3 python=3.6 pillow tensorflow=1.8
conda install -n python3 -c menpo opencv3
```

**Comment by watersink** [comment]
pip3 install tensorflow-gpu==1.8.0
pip3 install tensorflow==1.8.0
pip3 install opencv-python

**Comment by MrOCR** [comment]
@watersink after installing what you suggested to me, I ran `train_test.py`, and same error appear:
```
(python3) home@home-lnx:~/ocrsegment$ python3 train_test.py 
2018-09-19 15:19:09.302232: W tensorflow/core/framework/allocator.cc:101] Allocation of 1113262080 exceeds 10% of system memory.
2018-09-19 15:19:10.346583: W tensorflow/core/framework/allocator.cc:101] Allocation of 1113262080 exceeds 10% of system memory.
2018-09-19 15:19:15.695780: W tensorflow/core/framework/allocator.cc:101] Allocation of 278236160 exceeds 10% of system memory.
2018-09-19 15:19:24.179213: W tensorflow/core/framework/allocator.cc:101] Allocation of 556472320 exceeds 10% of system memory.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped
```

**Comment by MrOCR** [comment]
@watersink can I run training using only CPU?
