### ISSUE TITLE
Segmentation.py [AttributeError: 'NoneType' object has no attribute 'shape']

### ISSUE THREAD

**Issue by MrOCR** [watersink/ocrsegment#3]
@watersink Thank you for your hard work

I have successfully trained a new model using `train_test.py`.
[ocrseg.ckpt-200.zip](https://github.com/watersink/ocrsegment/files/2399122/ocrseg.ckpt-200.zip)

But when using my model for segmentation, an error message appears: 

```
home@home-lnx:~/ocrsegment$ python3 segmentation.py 
Traceback (most recent call last):
  File "segmentation.py", line 444, in <module>
    lines = seg.extract_textlines(image)
  File "segmentation.py", line 425, in extract_textlines
    if len(image.shape)!=2:
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by MrOCR** [comment]
I figured it out.
It was caused because `segmentation.py` line 443 had the wrong image name.
Change `W1P0.png` to `W001.png`
